// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Merge_Migrai : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Merge_Migrai));
        
        string IMigrationMetadata.Id
        {
            get { return "202011192050530_Merge_Migrai"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
